### PR TITLE
datasets -> only_datasets

### PR DESCRIPTION
**Pull request by vivbak**
Following comment here https://github.com/populationgenomics/cpg-utils/pull/80 ~~and in line with only_samples convention~~

### CODE REVIEW

**Comment by vladsavelyev** [comment]
What I don't like about it is that it creates a false impression that this option is optional, e.g. the workflow picks all "datasets" by default, and this option just narrows down the list, much like the `only_samples` option does. Though we could certainly make it work this way, if Metamist would have an endpoint to tell which datasets need to be processed for e.g. a seqr-loader run. We could start working into this direction

**Comment by vivbak** [comment]
Perhaps `input_datasets` is better then? Also, in this case what's the purpose of `skip_datasets`? Wouldn't you just not specify the dataset in `datasets`?

**Comment by vladsavelyev** [comment]
E.g. a list of datasets would be in one config, and `skip_datasets` could be in another config.

**Comment by vladsavelyev** [comment]
Let's name it `input_datasets` then.

And let's work on Metamist returning a list of datasets for seqr-loader instead of specifying it in the config

**Review by vladsavelyev — APPROVED** [review]

**Pull request merged**
